Senstay.Dojo.WebApp/Controllers/OwnerPaymentController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using NLog;
using Senstay.Dojo.Infrastructure;
using Senstay.Dojo.Data.Providers;
using Senstay.Dojo.Models;
using Senstay.Dojo.Models.View;
using Senstay.Dojo.Models.Grid;

namespace Senstay.Dojo.Controllers
{
    [Authorize]
    [CustomHandleError]
    public class OwnerPaymentController : AppBaseController
    {
        // a looger object per class is the recommended way of using NLog
        private static Logger DojoLogger = NLog.LogManager.GetCurrentClassLogger();
        private readonly DojoDbContext _dbContext;

        public OwnerPaymentController(DojoDbContext context)
        {
            _dbContext = context;
        }

        #region Custom methods

        public ActionResult Index()
        {
            if (!AuthorizationProvider.CanEditStatement()) return Forbidden();

            ViewBag.ReviewerClass = AuthorizationProvider.CanReviewRevenue() ? "revenue-grid-reviewer" : string.Empty;
            ViewBag.ApproverClass = AuthorizationProvider.CanApproveRevenue() ? "revenue-grid-approver" : string.Empty;
            ViewBag.FinalizerClass = AuthorizationProvider.CanFinalizeRevenue() ? "revenue-grid-finalizer" : string.Empty;
            ViewBag.EditClass = AuthorizationProvider.CanEditStatement() ? string.Empty : " revenue-field-readonly";
            ViewBag.AdminClass = AuthorizationProvider.IsRevenueAdmin() ? "revenue-grid-remover" : string.Empty;
            ViewBag.CanFreezeEditing = AuthorizationProvider.CanFreezeEditing() ? true : false;
            ViewBag.StatementCompleted = (new StatementCompletionProvider(_dbContext)).IsCompleted(DateTime.Today);

            return View();
        }

        [OutputCache(Duration = 0, NoStore = true)]
        public ActionResult PaymentEditor(DateTime month)
        {
            if (!AuthorizationProvider.CanEditStatement()) return Forbidden();
            try
            {
                var provider = new OwnerPaymentProvider(_dbContext);
                var editor = provider.GetPayoutBalancesForMonth(month);
                return PartialView("_PayoutMethodPaymentPartial", editor);
            }
            catch
            {
                return PartialView("_PayoutMethodPaymentPartial", new PayoutMethodPaymentEditModel());
            }
        }

        [OutputCache(Duration = 0, NoStore = true)]
        public ActionResult RebalanceEditor(int id, DateTime data)
        {
            if (!AuthorizationProvider.CanEditStatement()) return Forbidden();
            try
            {
                var provider = new OwnerPaymentProvider(_dbContext);
                var editor = provider.GetBalancesForPayoutMethod(id, data);
                return PartialView("_RebalancePartial", editor);
            }
            catch
            {
                return PartialView("_RebalancePartial", new RebalanceEditModel());
            }
        }

        [OutputCache(Duration = 0, NoStore = true)]
        public JsonResult RetrievePayoutMethodPayments(DateTime month)
        {
            if (!AuthorizationProvider.CanEditStatement()) return Forbidden();

            try
            {
                var provider = new OwnerPaymentProvider(_dbContext);
                var model = provider.Retrieve(month);
                return Json(model, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(new PayoutMethodPaymentViewModel(), JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult RedistributeBalance(List<PropertyBalance> balances)
        {
            if (!AuthorizationProvider.CanEditStatement()) return Forbidden();

            try
            {
                var provider = new PropertyBalanceProvider(_dbContext);
                provider.RedistributeBalance(balances);
                return Json("success", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult UpdateBalances(DateTime month)
        {
            if (!AuthorizationProvider.CanEditStatement()) return Forbidden();

            try
            {
                var provider = new PropertyBalanceProvider(_dbContext);
                provider.UpdateNextMonthBalances(month);
                return Json("success", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult IsEditFreezed(DateTime month)
        {
            try
            {
                // get the edit freeze flag
                var freezeProvider = new StatementCompletionProvider(_dbContext);
                int editFreezedFlag = !freezeProvider.Exist(month) ? -1 : freezeProvider.IsEditFreezed(month) ? 1 : 0;
                return Json(editFreezedFlag, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult FreezeEditing(DateTime month, bool freeze)
        {
            if (!AuthorizationProvider.CanFreezeEditing()) return Forbidden();

            try
            {
                var provider = new StatementCompletionProvider(_dbContext);
                provider.FreezeEditing(month, freeze);
                return Json(freeze ? "0" : "1", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }

        #endregion

        #region CRUD operations implementation

        public JsonResult SavePayoutMethodPayments(List<PayoutPayment> payments)
        {
            if (!AuthorizationProvider.CanEditStatement()) return Forbidden();

            try
            {
                // create/update payments
                var provider = new PayoutPaymentProvider(_dbContext);
                provider.SavePayoutMethodPayments(payments);

                // add a statement completion record for the payment month
                if (payments != null && payments.Count > 0)
                {
                    var nextMonth = (new DateTime(payments[0].PaymentYear, payments[0].PaymentMonth, 1)).AddMonths(1);
                    var completionProvider = new StatementCompletionProvider(_dbContext);
                    completionProvider.New(nextMonth);
                }

                return Json("success", JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult RedistributeBalances(List<PropertyBalance> balances)
        {
            if (!AuthorizationProvider.CanEditStatement()) return Forbidden();

            try
            {
                var provider = new PropertyBalanceProvider(_dbContext);
                provider.RedistributeBalance(balances);
                return Json("success", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }

        #endregion

        #region helper methods

        private JsonResult Forbidden()
        {
            string message = string.Format("User '{0}' does not have permission to access Owner Payment.", this.User.Identity.Name);
            DojoLogger.Warn(message, this.GetType());
            Response.StatusCode = (int)System.Net.HttpStatusCode.Forbidden;
            return Json(new OtherRevenueModel(), JsonRequestBehavior.AllowGet);
        }

        private JsonResult InternalError(string logMsg, string returnMsg, Exception ex = null)
        {
            string message = string.Empty;
            if (ex != null)
                message = string.Format("{0} - {1}", logMsg, ex.Message + ex.StackTrace);
            else
                message = string.Format("{0}", logMsg);

            DojoLogger.Error(message, this.GetType());
            Response.StatusCode = (int)System.Net.HttpStatusCode.InternalServerError;
            return Json(new OtherRevenueModel(), JsonRequestBehavior.AllowGet);
        }

        #endregion
    }
}

Senstay.Dojo.WebApp/Views/OwnerPayment/Index.cshtml
@{
    ViewBag.App = "SenStay Dojo App";
    ViewBag.Title = "Owner Payments";
    ViewBag.PageHint = "Payment";

    var defaultMonth = DateTime.Today.AddMonths(-1).ToString("MMMM yyyy");
    var editDisabled = ViewBag.StatementCompleted == true ? "hide" : "";
    var editEnabled = ViewBag.StatementCompleted == false ? "hide" : "";
}

<div class="ss-page-content">
    <div class="revenue-page-title revenue-h2">@ViewBag.Title <span id="dataCount"></span></div>
    <div class="row">
        <div class="revenue-filters">
            <div class="float-left statement-filter-item300 statement-filter-margin">
                <div class="control-group">
                    <div class="input-group revenue-input-item">
                        <div class="input-group-addon"><span class="fa fa-calendar"><span> Month</span></span></div>
                        <input id="paymentMonth" value="@defaultMonth" title="Payment Month" />
                    </div>
                </div>
            </div>

            @if (ViewBag.EditClass == string.Empty)
            {
                if (ViewBag.CanFreezeEditing == true)
                {
                    <!-- disable statement/revenue/payment editing -->
                    <div class="float-left">
                        <div id="disableEditButton" class="finalize-button @editDisabled">
                            <div class="revenue-button" style="margin-left:10px;">
                                <a id="disableEdit">&nbsp;&nbsp;<span class="finalizeText">Disable Statement/Revenue/Payment Editing</span>&nbsp;&nbsp;</a>
                            </div>
                        </div>
                    </div>
                    <!-- enable statement/revenue/payment editing -->
                    <div class="float-left">
                        <div id="enableEditButton" class="finalize-button @editEnabled">
                            <div class="revenue-button" style="margin-left:10px;">
                                <a id="enableEdit">&nbsp;&nbsp;<span class="finalizeText">Enable Statement/Revenue/Payment Editing</span>&nbsp;&nbsp;</a>
                            </div>
                        </div>
                    </div>
                }

                <!-- finalize payments -->
                <div class="float-left">
                    <div id="beginBalanceButton" class="finalize-button">
                        <div class="revenue-button" style="margin-left:10px;">
                            <a id="updateBalances">&nbsp;&nbsp;<span class="finalizeText">Create/Update Beginning Balances for Next Month</span>&nbsp;&nbsp;</a>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="clearfix"></div>
    </div>

    <!-- action alert when there is notice -->
    <div id="payment-alert" class="alert-container"></div>

    <div class="revenue-data-grid">
        <div id="payoutMethodGrid" class="revenue-grid @ViewBag.ReviewerClass @ViewBag.ApproverClass @ViewBag.FinalizerClass @ViewBag.AdminClass @ViewBag.EditClass"></div>
    </div>

    <!-- slding out alert messaging -->
    <div id="actionAlert" class="alert-container"></div>
</div >

@Html.Partial("_DialogPartial")

@Html.Partial("_ConfirmationDialog")

@section CustomFormStyle
{
    <style type="text/css">
        body {overflow:hidden;}
        #formDialog input.input-sm { margin-bottom: 0px !important; }
        .dialog-page-content { padding:0px 0px 20px 20px; }
        html .k-grid tr:hover { background: transparent; }
        html .k-grid tr.k-alt:hover { background: #f1f1f1; }
        .k-grid-content .k-detail-cell .k-grid {width:600px;}
        /* this will remove spinner from numeric grid cell editor */
        .k-numerictextbox .k-select { display: none; }
        .k-numerictextbox .k-numeric-wrap { padding-right: 2px; }
    </style>
}

@section styles
{
    <link rel="Stylesheet" href="@Href("~/content/app/appForm.css")" />
    <link rel="Stylesheet" href="@Href("~/content/app/revenue.css")" />
}

@section scripts
{
    @Scripts.Render("~/bundles/inputmask")
    @Scripts.Render("~/Scripts/app/ownerpayment.js" + ViewBag.Release)

    <script type="text/javascript">
        $(document).ready(function () {
            DojoWeb.PayoutMethodPayment.init('payoutMethodGrid');
        });
    </script>
}

Senstay.Dojo.WebApp/Views/OwnerPayment/_PayoutMethodPaymentPartial.cshtml
@model Senstay.Dojo.Models.View.PayoutMethodPaymentEditModel

<div class="dialog-page-content">
    @using (Ajax.BeginForm("PaymentEditor", "OwnerPayment", new AjaxOptions
        {
            HttpMethod = "POST",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "edit-ajax-target",
            LoadingElementId = "edit-ajax-wait",
            OnSuccess = "DojoWeb.PaymentEditor.refresh",
            OnFailure = "DojoWeb.PaymentEditor.serverError"
        },
        new { @id = "PayoutMethodPaymentForm", @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div class="payout-payment-view">
            <div>
                <div class="payment-actionbar float-left">(<span class="payment-edit-text-color">colored</span> cells are editable)</div>
                <div class="payment-actionbar float-right"><a id="suggestedPayments">&nbsp;&nbsp;Apply Suggested Payments&nbsp;&nbsp;</a></div>
            </div>
            <div class="clearfix"></div>
            <table class="payout-payment-table" cellpadding="0" cellspacing="0">
                <tr class="payment-header">
                    <td class="payout-payment-col-1">Payout Method</td>
                    <td class="payout-payment-col-2">Begin Balance</td>
                    <td class="payout-payment-col-2">Total Balance</td>
                    <td class="payout-payment-col-3">Payment</td>
                    <td class="payout-payment-col-2">Carry Over</td>
                    <td class="hide"></td>
                    <td class="hide"></td>
                    <td class="hide"></td>
                    <td class="hide"></td>
                </tr>
                @for (int i = 0; i < Model.Payments.Count; i++)
                {
                    <tr class="payment-row">
                        <td class="payout-payment-col-1"><span class="methodName">@Model.Payments[i].PayoutMethodName</span></td>
                        <td class="payout-payment-col-2">
                            <span class="payment-begin-balance">
                                @if (Model.Payments[i].BeginBalance != null)
                                {
                                    @Model.Payments[i].BeginBalance.Value.ToString("c2") 
                                }
                            </span>
                        </td>
                        <td class="payout-payment-col-2">
                            <span class="payment-total-balance">
                                @if (Model.Payments[i].TotalBalance != null)
                                { 
                                    @Model.Payments[i].TotalBalance.Value.ToString("c2") 
                                }
                            </span>
                        </td>
                        <td class="payout-payment-col-3 payment-edit-color"><input type="text" id=@($"payment-item-{i}") name=@($"payment-item-{i}") class="payment-item payment-edit-color" value="@Model.Payments[i].PaymentAmount" /></td>
                        <td class="payout-payment-col-2">
                            @if (Model.Payments[i].CarryOver != null) { @Model.Payments[i].CarryOver.Value.ToString("c2") }
                        </td>
                        <td class="hide"><div class="methodId">@Model.Payments[i].PayoutMethodId</div></td>
                        <td class="hide"><div class="paymentId">@Model.Payments[i].PayoutPaymentId</div></td>
                        <td class="hide"><div class="paymentMonth">@Model.Payments[i].PaymentMonth</div></td>
                        <td class="hide"><div class="paymentYear">@Model.Payments[i].PaymentYear</div></td>
                    </tr>
                }
            </table>
            
        </div>

        <!-- Action buttons -->
        if (string.IsNullOrEmpty(ViewBag.EditClass))
        {
            <div class="form-action-button">
                <input id="PaymentSave" type="button" value="Save Payments" class="btn btn-success btn-default btn-spacing" />
                <input id="PaymentCancel" type="button" value="Cancel" class="btn btn-warning" />
            </div>
        }
    }
</div>

Senstay.Dojo.WebApp/Views/OwnerPayment/_RebalancePartial.cshtml
@model Senstay.Dojo.Models.View.RebalanceEditModel

<div class="dialog-page-content">
    @using (Ajax.BeginForm("RebalanceEditor", "OwnerPayment", new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "edit-ajax-target",
        LoadingElementId = "edit-ajax-wait",
        OnSuccess = "DojoWeb.RebalanceEditor.refresh",
        OnFailure = "DojoWeb.RebalanceEditor.serverError"
    },
        new { @id = "RealanceEntryForm", @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div class="rebalance-view">
            <div>
                <div class="rebalance-actionbar balanceTotal float-left">Total Balance:
                        @for (int i = 0; i < Model.Balances.Count; i++)
                        {
                            if (Model.Balances[i].IsSummary == true)
                            {
                                <span>@Model.Balances[i].BeginningBalance.Value.ToString("c2")</span>
                                break;
                            }
                        }
                </div>
                <div class="rebalance-actionbar float-right"><a id="defaultRebalance">&nbsp;&nbsp;Apply Default Rules&nbsp;&nbsp;</a></div>
            </div>
            <div class="clearfix"></div>
            <table class="rebalance-table" cellpadding="0" cellspacing="0">
                <tr class="rebalance-header">
                    <td class="rebalance-col-1">Property Code</td>
                    <td class="rebalance-col-1">Rebalance Month</td>
                    <td class="rebalance-col-2">Property Balance</td>
                    <td class="rebalance-col-3">Adjusted Balance</td>
                    <td class="hide"></td>
                    <td class="hide"></td>
                </tr>
                @for (int i = 0; i < Model.Balances.Count; i++)
                {
                    if (Model.Balances[i].IsSummary == false)
                    {
                        <tr class="rebalance-row">
                            <td class="rebalance-col-1"><span class="propertyCode">@Model.Balances[i].PropertyCode</span></td>
                            <td class="rebalance-col-1">@Model.Balances[i].Month/@Model.Balances[i].Year</td>
                            <td class="rebalance-col-2"><span class="beginBalance">@Model.Balances[i].BeginningBalance.Value.ToString("c2")</span></td>
                            <td class="rebalance-col-3 rebalance-edit-color"><input type="text" id=@($"rebalance-item-{i}") name=@($"rebalance-item-{i}") class="rebalance-item rebalance-edit-color" value="@Model.Balances[i].AdjustedBalance" /></td>
                            <td class="hide"><div class="rebalanceMonth">@Model.Balances[i].Month</div></td>
                            <td class="hide"><div class="rebalanceYear">@Model.Balances[i].Year</div></td>
                        </tr>
                    }
                }
            </table>
            
        </div>

        <!-- Action buttons -->
        if (string.IsNullOrEmpty(ViewBag.EditClass))
        {
            <div class="form-action-button">
                <input id="RebalanceSave" type="button" value="Save Balance" class="btn btn-success btn-default btn-spacing" />
                <input id="RebalanceCancel" type="button" value="Cancel" class="btn btn-warning" />
            </div>
        }
    }
</div>